### ISSUE TITLE
failed to interpret wav file as a pickle (while running seld.py)

### ISSUE THREAD

**Issue by elyorman** [sharathadavanne/seld-dcase2020#6]
![Screenshot from 2020-07-15 18-06-11](https://user-images.githubusercontent.com/60263344/87526902-5b8ccd80-c6c6-11ea-8fbd-562a87b661fb.png)

Having this issue while running seld.py script. Could anyone help me figure it out?

**Comment by sharathadavanne** [comment]
Your error says that you are reading a wave recordings as a pickle file. This should not have never happened.
Did you do any other code changes before running this repo? 
Did you follow all the steps [given here](https://github.com/sharathadavanne/seld-dcase2020#training-the-seldnet) correctly?

**Comment by elyorman** [comment]
I am following each step and did not make any changes in code except for paths. And actually I got pass through this issue and was able to extract features by running python3 batch_feature_extraction.py. and now I am having another error while running seld.py. 
![image](https://user-images.githubusercontent.com/60263344/87628747-98130480-c76c-11ea-9e4d-a78d7b9529fb.png)

**Comment by sharathadavanne** [comment]
Can you share the complete error log, the one shared above is partial, and it is not helpful.

**Comment by elyorman** [comment]
`Traceback (most recent call last):
  File "seld.py", line 345, in <module>
    sys.exit(main(sys.argv))
  File "seld.py", line 166, in main
    weights=params['loss_weights'], doa_objective=params['doa_objective'])
  File "C:\Users\Admin\ELYOR\projects\task_3\seld-dcase2020-master\keras_model.py", line 41, in get_model
    )(spec_rnn)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\layers\wrappers.py", line 531, in __call__
    return super(Bidirectional, self).__call__(inputs, **kwargs)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 897, in __call__
    self._maybe_build(inputs)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 2416, in _maybe_build
    self.build(input_shapes)  # pylint:disable=not-callable
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\layers\wrappers.py", line 685, in build
    self.forward_layer.build(input_shape)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent_v2.py", line 388, in build
    super(GRU, self).build(input_shape)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 573, in build
    self.cell.build(step_input_shape)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\utils\tf_utils.py", line 316, in wrapper
    output_shape = fn(instance, input_shape)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\layers\recurrent.py", line 1752, in build
    caching_device=default_caching_device)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer.py", line 577, in add_weight
    caching_device=caching_device)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\training\tracking\base.py", line 743, in _add_variable_with_custom_getter
    **kwargs_for_getter)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer_utils.py", line 141, in make_variable
    shape=variable_shape if variable_shape else None)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 259, in __call__
    return cls._variable_v1_call(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 220, in _variable_v1_call
    shape=shape)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 198, in <lambda>
    previous_getter = lambda **kwargs: default_variable_creator(None, **kwargs)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\ops\variable_scope.py", line 2598, in default_variable_creator
    shape=shape)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\ops\variables.py", line 263, in __call__
    return super(VariableMetaclass, cls).__call__(*args, **kwargs)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1434, in __init__
    distribute_strategy=distribute_strategy)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\ops\resource_variable_ops.py", line 1567, in _init_from_args
    initial_value() if init_from_fn else initial_value,
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\keras\engine\base_layer_utils.py", line 121, in <lambda>
    init_val = lambda: initializer(shape, dtype=dtype)
  File "C:\Users\Admin\anaconda3\lib\site-packages\tensorflow\python\ops\init_ops_v2.py", line 548, in __call__
    scale /= max(1., (fan_in + fan_out) / 2.)
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'`

here it is. thank you in advance

**Comment by anam-z** [comment]
Hello
I have been trying to run seld.py but get the above error. Did the above issue resolve?
